### ISSUE TITLE
Info statements not consistant

### ISSUE THREAD

**Issue by 9000h** [pesintta/vdr-plugin-vaapidevice#107]
https://github.com/pesintta/vdr-plugin-vaapidevice/blob/337bf074a997f0425576be14caacd7dd748ff09a/video.c#L1845
it's not the only one
```
Mar 15 21:53:56 acer533 vdr: [10512] VAAPI: video/vaapi: allocating 1 forward reference surfaces for postprocessing
Mar 15 21:53:56 acer533 vdr: [10512] VAAPI: video/vaapi: allocating 0 backward reference surfaces for postprocessing
Mar 15 21:53:56 acer533 vdr: [10512] VAAPI: Changing to 0 forward reference surfaces for postprocessing
```

**Comment by pesintta** [comment]
Depending on the source material and enabled filters there isn't always need to have the same exact number of reference surfaces that were allocated in the beginning. The actually needed surfaces are queried from the driver for each frame before running filters.

In my opinion the distinction is quite clear in the message (allocating vs. changing) so I'm inclined to simply close this issue.

**Comment by 9000h** [comment]
you may misunderstood, the request was only in regards of the "video/vaapi:" prefix

**Comment by pesintta** [comment]
Ah, indeed. I'll fix the log format in an upcoming commit.
