### ISSUE TITLE
ColorBalance sizeof ?

### ISSUE THREAD

**Issue by 9000h** [pesintta/vdr-plugin-vaapidevice#109]
https://github.com/pesintta/vdr-plugin-vaapidevice/blob/38f9b210da66f17b946f627d98028f426e3b944d/video.c#L2515

I'm wondering if this should not be  sizeof(cbal_param)

**Comment by pesintta** [comment]
I don't think so. The next parameter is the number of items in the buffer so the sizeof refers to the size of 1 element.

**Comment by 9000h** [comment]
then I did misunderstood the documentation "a buffer for "num_elements" elements of "size" bytes"
http://01org.github.io/libva_staging_doxygen/group__api__core.html#gaba254978bf0d32781f4a9e67f1fa7a78
