### ISSUE TITLE
log black surface as error?

### ISSUE THREAD

**Issue by 9000h** [pesintta/vdr-plugin-vaapidevice#114]
https://github.com/pesintta/vdr-plugin-vaapidevice/blob/02a7b844bd0ff50d32ab8e456e222216830cb1c8/video.c#L3472
should displaying the black surface really shown as error as this is normal behavior info should be fine

**Comment by pesintta** [comment]
The code linked above actually utilizes level '2' which maps to debug logging in VaapiMessage()
