### ISSUE TITLE
Implemente needed Patches

### ISSUE THREAD

**Issue by P3f68** [pesintta/vdr-plugin-vaapidevice#35]
Please implemente needed Patches, related on the based softhddevice Fork:

--- softhddevice/codec.c.orig   2014-04-17 14:33:12.000000000 +0200
+++ softhddevice/codec.c        2014-04-28 20:58:15.850120324 +0200
@@ -59,6 +59,7 @@

 #include <alsa/iatomic.h>
 #include <libavcodec/avcodec.h>
+#include <libavutil/channel_layout.h>
 #include <libavutil/mem.h>
 // support old ffmpeg versions <1.0
 #if LIBAVCODEC_VERSION_INT < AV_VERSION_INT(55,18,102)

and

--- softhddevice-2014.04.17/Makefile.orig       2014-05-14 10:38:23.106431350 +0200
+++ softhddevice-2014.04.17/Makefile    2014-05-15 21:42:06.570275744 +0200
@@ -68,6 +68,7 @@

 export CFLAGS  = $(call PKGCFG,cflags)
 export CXXFLAGS = $(call PKGCFG,cxxflags)
+export PKG_CONFIG_PATH=/opt/ffmpeg/lib/pkgconfig

 ifeq ($(CFLAGS),)
 $(warning CFLAGS not set)

**Comment by 9000h** [comment]
your sources are from 2014?

**Comment by pesintta** [comment]
Looks like too old version of ffmpeg. The above avcodec.h should #include channel_layout.h in modern vesions.

PKG_CONFIG_PATH can be set through environment variables and there should be no need to hardcode them in Makefile
