### ISSUE TITLE
Playing old *.vdr recordings broken

### ISSUE THREAD

**Issue by Quantomax** [pesintta/vdr-plugin-vaapidevice#40]
If I play old *.vdr (1.6.x recordings), I only get about top 10% of picture, rest is more or less light grey.
It worked surely with git from around new year 2018, playing "A dinner for one" without problems.

Maybe caused by the new TS-Parser, as that are PES recordings?

----
Feb 12 01:05:15 vdr: video: slow down video, duping frame
Feb 12 01:05:15 vdr: video:  0:50:42.525  +65  625   0/\ms 182+5 v-buf
Feb 12 01:05:15 vdr: video: speed up video, droping frame
Feb 12 01:05:15 vdr: video:  0:50:42.525  +26  681   0/\ms 182+3 v-buf
Feb 12 01:05:15 vdr: audio/alsa: using device 'stereo'
Feb 12 01:05:15 vdr: audio/alsa: start delay 336ms
Feb 12 01:05:15 vdr: video: slow down video, duping frame
Feb 12 01:05:15 vdr: video:  0:51:42.285 +300  427   0/\ms  59+5 v-buf
Feb 12 01:05:15 vdr: [vaapidevice] empty video packet 56 bytes
Feb 12 01:05:15 vdr: video/vaapi: synced after 25 frames
Feb 12 01:05:15 vdr: video: slow down video, duping frame
Feb 12 01:05:15 vdr: video: speed up video, droping frame
Feb 12 01:05:15 vdr: video:  0:51:42.565  +20  587   0/\ms 182+3 v-buf
Feb 12 01:05:15 vdr: video: slow down video, duping frame
Feb 12 01:05:15 vdr: video:  0:51:42.645  +60  571   0/\ms 182+5 v-buf
Feb 12 01:05:16 vdr: video: speed up video, droping frame
Feb 12 01:05:16 vdr: video:  0:51:42.645  +20  675   0/\ms 182+3 v-buf
Feb 12 01:05:16 vdr: video: slow down video, duping frame
Feb 12 01:05:16 vdr: video:  0:51:42.725  +60  659   0/\ms 182+5 v-buf
Feb 12 01:05:16 vdr: video: speed up video, droping frame
Feb 12 01:05:16 vdr: video:  0:51:42.725  +20  643   0/\ms 182+3 v-buf
Feb 12 01:05:16 vdr: [vaapidevice] empty video packet 2048 bytes
Feb 12 01:05:16 vdr: [vaapidevice] empty video packet 1137 bytes
Feb 12 01:05:16 vdr: video: slow down video, duping frame
Feb 12 01:05:16 vdr: video:  0:51:42.805  +59  626   0/\ms 182+5 v-buf
Feb 12 01:05:16 vdr: [vaapidevice] empty video packet 2048 bytes
Feb 12 01:05:16 vdr: video: speed up video, droping frame
Feb 12 01:05:16 vdr: video:  0:51:42.805  +20  587   0/\ms 182+3 v-buf
Feb 12 01:05:16 vdr: [vaapidevice] empty video packet 2048 bytes
Feb 12 01:05:16 vdr: [vaapidevice] empty video packet 1498 bytes
Feb 12 01:05:16 vdr: video: slow down video, duping frame
Feb 12 01:05:16 vdr: video:  0:51:42.885  +60  619   0/\ms 182+5 v-buf
Feb 12 01:05:16 vdr: video: speed up video, droping frame
Feb 12 01:05:16 vdr: video:  0:51:42.885  +20  627   0/\ms 182+3 v-buf
Feb 12 01:05:16 vdr: audio/alsa: using device 'stereo'
Feb 12 01:05:16 vdr: video: slow down video, duping frame
Feb 12 01:05:16 vdr: video:  0:52:42.765 +256  360   0/\ms  45+5 v-buf
Feb 12 01:05:16 vdr: audio/alsa: start delay 336ms
Feb 12 01:05:16 vdr: [vaapidevice] empty video packet 26 bytes
[..]

**Comment by rofafor** [comment]
You might be correct, but I don't have any PES recordings anymore available for testing/developing.

**Comment by Quantomax** [comment]
You can find a 10 seconds sample recording (PAL, SD, Testchart) at:
[PAL-Test.zip](http://www.hachmann-it.de/downloads/PAL-Test.zip)

**Comment by rofafor** [comment]
A (possible) fix can be found here: https://github.com/pesintta/vdr-plugin-vaapidevice/pull/54
