### ISSUE TITLE
true author

### ISSUE THREAD

**Issue by j1rie** [pesintta/vdr-plugin-vaapidevice#42]
The commit https://github.com/rofafor/vdr-plugin-vaapidevice/commit/45a7d485a35d90e641ad25c691c1acd72e44b48b is original from https://github.com/j1rie/softhddevice/commit/5708242c0aa18ebd606913b0a33138f39d9d6359
It helped once during my experiments two years ago, but I never invested time to find out, if it was needed under regular conditions. That's why I did not propose it in my previous series of pull requests.
Just wanted to mention this.

**Comment by pesintta** [comment]
Thanks for letting me know. What would you like to do here?
I can e.g. revert the patch and you can send me a proper pull-request with the right patch credentials or?

**Comment by 9000h** [comment]
I don't mind if my name is credited or not in the commit

**Comment by j1rie** [comment]
@9000h What was the reason, you proposed my patch? Did you run into a situation, where it was actually needed?

**Comment by 9000h** [comment]
@j1rie 
I did found it in my own version and still not fixed upstream.
I had no intention to hijack it you.
