### ISSUE TITLE
Screensaver inhibitor

### ISSUE THREAD

**Issue by mighty-p** [pesintta/vdr-plugin-vaapidevice#60]
The original softhddevice plugin has code to turn off DPMS and some screensavers (e.g. the gnome screensaver). Apparently this code was removed from vaapidevice. 

I believe it would be good to add again code to inhibit screensavers (maybe it can be done more generically, since the code in softhddevice seems only to tackle DPMS and some screensavers, but not all)-

**Comment by rofafor** [comment]
I haven't experienced any screensaver issues with the current master. You can always tweak dpms settings via xset: ```xset -dpms s off```

**Comment by mighty-p** [comment]
Switching DPMS and the screensaver manually of (for example with the command you provided) certainly helps. Therefore this idea is not urgent. Still other media players (e.g. vlc) have some code that make sure that screensavers don't kick in if something is played - even when the screensavers are activated. I thought that would be a nice feature for vaapidevice and actually the old softhddevice had such functionality built in at least partially.
