### ISSUE TITLE
unneeded vaSyncSurface ?

### ISSUE THREAD

**Issue by 9000h** [pesintta/vdr-plugin-vaapidevice#74]
https://github.com/pesintta/vdr-plugin-vaapidevice/blob/9da06d67dac1c77231787538e98635403c891059/video.c#L2713

did not make a difference here with and without

**Comment by pesintta** [comment]
The sync here is to make sure we don't draw a surface that is still rendering. Though maybe not necessary the vaSyncSurface() does not have performance effects for finished surfaces so I'd rather keep it.
