### ISSUE TITLE
probably not needed here

### ISSUE THREAD

**Issue by 9000h** [pesintta/vdr-plugin-vaapidevice#75]
https://github.com/pesintta/vdr-plugin-vaapidevice/blob/9da06d67dac1c77231787538e98635403c891059/video.c#L2712

**Comment by pesintta** [comment]
The xcb_flush() call here makes sure no output is buffered and waiting to be processed by Xorg. It might not be necessary but there's not a lot of performance effect either so I'd like to keep it for now.
