### ISSUE TITLE
OSD on windowed start is messed up

### ISSUE THREAD

**Issue by 9000h** [pesintta/vdr-plugin-vaapidevice#76]
the OSD on windowed start is messed up until vdr get noticed about the size change
![screenshot from 2018-03-07 21-45-01](https://user-images.githubusercontent.com/3009073/37117233-f0939ba6-2250-11e8-911f-fc82b4d29e8d.png)

**Comment by pesintta** [comment]
Can you split this into separate cases so we could track each issue individually?

**Comment by mighty-p** [comment]
for me, the OSD works with current git state only in fullscreen. Otherwise it looks similar to 9000h's screenshot above.

**Comment by pesintta** [comment]
I'll push a change that fixes this for me. Please reopen issue if OSD is still broken.

**Comment by mighty-p** [comment]
I confirm that this commit fixes the problem for me.

**Comment by 9000h** [comment]
works fine now

**Comment by 9000h** [comment]
would be great for the other users to backport it to the deprecated branch

**Comment by rofafor** [comment]
The other users should really switch to the master branch rather than using the deprecated vpp_support branch. If you meant VDPAU, that feature was never supported in this fork.
