### ISSUE TITLE
CPU high io wait

### ISSUE THREAD

**Issue by 9000h** [pesintta/vdr-plugin-vaapidevice#80]
high cpu io wait, which did probably not come from vaapidevice and is also no disk io
![screenshot from 2018-03-07 21-49-05](https://user-images.githubusercontent.com/3009073/37117391-63765596-2251-11e8-9fea-9624da152300.png)

**Comment by pesintta** [comment]
This issue does not look like its related to code in vaapidevice so I'm closing it.
