### ISSUE TITLE
false color issue

### ISSUE THREAD

**Issue by 9000h** [pesintta/vdr-plugin-vaapidevice#83]
if you went in full screen mode to the vaapidevice plugin settings and then go back the video colors are wrong. If you switch then to windowed mode the colors are back to normal.
![screenshot from 2018-03-08 20-41-25](https://user-images.githubusercontent.com/3009073/37172605-9952cb16-2311-11e8-9477-62e6a7e20286.png)

**Comment by jupe76** [comment]
I can confirm this one.
I have it since "ever" :-)

**Comment by Space2Man** [comment]
I have seen this happen also I change e.g. the deinterlacer settings or some other post-processing

**Comment by 9000h** [comment]
it's 720p h.264 on my screenshot

**Comment by pesintta** [comment]
I made a change in the contrast/saturation initialization values. Does this fix the bug?

**Comment by 9000h** [comment]
unfortunatley not

**Comment by pesintta** [comment]
Can you edit the values in the commit https://github.com/pesintta/vdr-plugin-vaapidevice/commit/238925f4acdb8a6534208ccfc52b195f4176c43d and use ConfigVideoContrast = 1 instead of 10?

Also try ConfigVideoSaturation = 1. It may be that I used too large values still.

If that doesn't help the issue must be elsewhere.

**Comment by 9000h** [comment]
I did set both to 1 and the issue is gone :-)

**Comment by pesintta** [comment]
Thanks for testing!

**Comment by 9000h** [comment]
but wait, does that not imply that the settings saved in the setup.conf get not applied at start?

**Comment by pesintta** [comment]
I don't think so but you can test that by setting large or wrong values in your setup.conf and seeing the effects on screen. If they are not working as they should you can open a new issue.
