### ISSUE TITLE
center cut-out broken latest version

### ISSUE THREAD

**Issue by geraldraaf** [pesintta/vdr-plugin-vaapidevice#89]
Hi,

center cut-out is broken in the latest Versions, this happens with HD and SD recordings.
I have updated my vaapidevice installation from 1.0.0-GIT6372704 to 1.0.0-GIT7ef6ad5. I have recognized that center cut-out is broken.
I have attached 3 Pictures from a SD recording, this recording is a TS recording, but it also happens with PES recordings.

Original
![original](https://user-images.githubusercontent.com/1211289/37241860-6237c780-2460-11e8-8aea-2c85c99fb479.jpg)
Working
![working_center_cut-out](https://user-images.githubusercontent.com/1211289/37241861-627b14cc-2460-11e8-996b-cf39aeff5216.jpg)
Not working
![not_working_center_cut_out](https://user-images.githubusercontent.com/1211289/37241862-62b3ce66-2460-11e8-8ef4-acc9991d38fd.jpg)

**Comment by geraldraaf** [comment]
------------------------------------------------------------------------------
                 VAAPIDEVICE SYSTEM DEBUG INFORMATION REPORT                  
------------------------------------------------------------------------------
System:    Kernel: 4.15.4-gentoo x86_64 bits: 64 gcc: 6.4.0
           Desktop: LXDE (Openbox 3.6.1)
           Distro: Gentoo Base System release 2.4.1
Machine:   Device: laptop System: LENOVO product: 20CD000MGE v: ThinkPad S1 Yoga serial: N/A
           Mobo: LENOVO model: 20CD000MGE v: SDK0E50510 Pro serial: N/A
           UEFI: LENOVO v: GQET42WW (1.22 ) date: 01/08/2015
CPU:       Dual core Intel Core i5-4200U (-MT-MCP-) 
           arch: Haswell rev.1 cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 9178
           clock speeds: max: 2600 MHz 1: 2029 MHz 2: 1693 MHz 3: 1980 MHz
           4: 1640 MHz
Graphics:  Card: Intel Haswell-ULT Integrated Graphics Controller
           bus-ID: 00:02.0
           Display Server: x11 (X.Org 1.19.5 ) driver: modesetting
           Resolution: 1920x1080@60.04hz, 1920x1200@59.95hz, 1920x1200@59.95hz
           OpenGL: renderer: Mesa DRI Intel Haswell Mobile
           version: 4.5 Mesa 17.2.8 Direct Render: Yes
Audio:     Card-1 Intel 8 Series HD Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0
           Card-2 Intel Haswell-ULT HD Audio Controller
           driver: snd_hda_intel bus-ID: 00:03.0
           Card-3 Lenovo driver: USB Audio usb-ID: 002-007
           Sound: Advanced Linux Sound Architecture v: k4.15.4-gentoo
Network:   Card: Intel Wireless 7260 driver: iwlwifi bus-ID: 04:00.0
Info:      Processes: 209 Uptime: 5:41 Memory: 4074.2/7882.8MB
           Init: SysVinit rc: OpenRC runlevel: default Gcc sys: 6.4.0
           Client: Shell (generate_system) inxi: 2.3.55 
------------------------------------------------------------------------------
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 2.1.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
------------------------------------------------------------------------------
                  INCLUDE THIS REPORT INTO YOUR GITHUB ISSUE                  
------------------------------------------------------------------------------

**Comment by rofafor** [comment]
Sorry, I forgot a parameter to protect privacy in my system report script and you already used it. You should modify your post by deleting serial numbers or simply re-run the updated script.

**Comment by rofafor** [comment]
Please, check whether the https://github.com/pesintta/vdr-plugin-vaapidevice/pull/101 fixes your problem.

**Comment by geraldraaf** [comment]
Pull request https://github.com/pesintta/vdr-plugin-vaapidevice/pull/101 will solve the broken center cut-out issue.
