### ISSUE TITLE
No picture 

### ISSUE THREAD

**Issue by Saman-VDR** [pesintta/vdr-plugin-vaapidevice#92]
Hi, I didn't get a picture anymore.
For me, the last working commit is 6372704835b62bee882feed92686edc75e70b55f

Mar 10 16:52:30 vdr vdr: [4170] VAAPI: video/vaapi: supports unscaled osd
Mar 10 16:52:30 vdr vdr: [4170] VAAPI: audio: 'alsa' output module used
Mar 10 16:52:30 vdr vdr: [4170] VAAPI: audio/alsa: supports pause: yes
Mar 10 16:52:30 vdr vdr: [4365] VAAPI-ERROR: video/vaapi: can't destroy 8 surfaces
Mar 10 16:52:30 vdr vdr: [4365] VAAPI-ERROR: video/vaapi: can't destroy postproc context!
Mar 10 16:52:30 vdr vdr: [4365] VAAPI-ERROR: video/vaapi: can't destroy config!

 ------------------------------------------------------------------------------
                 VAAPIDEVICE SYSTEM DEBUG INFORMATION REPORT                  
------------------------------------------------------------------------------

System:    Kernel: 4.15.0-11-generic x86_64 bits: 64 gcc: 7.3.0 Console: tty 1
           Distro: Ubuntu Bionic Beaver (development branch)
Machine:   Device: desktop Mobo: ASRock model: J3455M serial: N/A UEFI: American Megatrends v: P1.40 date: 07/14/2017
CPU:       Quad core Intel Celeron J3455 (-MCP-) arch: N/A cache: 1024 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 11980
           clock speeds: max: 2300 MHz 1: 1618 MHz 2: 1768 MHz 3: 2018 MHz 4: 1523 MHz
Graphics:  Card: Intel Device 5a85 bus-ID: 00:02.0
           Display Server: N/A drivers: modesetting (unloaded: fbdev,vesa)
           tty size: 136x28 Advanced Data: N/A out of X
Audio:     Card Intel Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster
           driver: snd_hda_intel bus-ID: 00:0e.0
           Sound: Advanced Linux Sound Architecture v: k4.15.0-11-generic
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: e000 bus-ID: 01:00.0
Info:      Processes: 239 Uptime: 1:04 Memory: 3664.5/7386.2MB Init: systemd runlevel: 5 Gcc sys: 7.3.0
           Client: Shell (generate_system) inxi: 2.3.56 

------------------------------------------------------------------------------

vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Broxton - 2.0.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD

------------------------------------------------------------------------------
                  INCLUDE THIS REPORT INTO YOUR GITHUB ISSUE                  
------------------------------------------------------------------------------

**Comment by rofafor** [comment]
You're trying to use the kernel modesetting output, that's not yet supported. Please, define the correct X11 display via the command-line parameter ```-d```.

**Comment by Saman-VDR** [comment]
Thank you very much, problem is solved.
