### ISSUE TITLE
Line artefacts in 1080p (HEVC, German DVB-T2) in window mode

### ISSUE THREAD

**Issue by mighty-p** [pesintta/vdr-plugin-vaapidevice#94]
I detected another issue that was not present for me with the old softhddevice/pesintta code before the rename to vaapidevice.

For DVB-T2 channels which are broadcast here in HEVC with 1080p resolution, in windowed mode, there are line artefacts in the picture. They disappear in fullscreen. Also in windowed mode, when I resize the window, sometimes they appear, sometimes they disappear (until I resize again the window). The problem does not happen with channels in other resolutions such as 1080i, 720p or SDTV. Only 1080p seems affected.

![vaapidevice-artefacts-in-1080phevc](https://user-images.githubusercontent.com/36699890/37252057-391e3bf2-251b-11e8-829c-43bed3df3a7c.png)

**Comment by mighty-p** [comment]
I now also tried the latest ffmpeg snapshot (from http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2). With this, the problem here is gone, but in turn, the image is not scaled anymore (i.e. in windowed mode, I only see the upper left extract of the 1080p image). I believe with that ffmpeg version, simply no post-processing happens, which triggers again the issue that apparently current vaapidevice does not apply scaling when no post-processing happens (see https://github.com/pesintta/vdr-plugin-vaapidevice/issues/86).

**Comment by mighty-p** [comment]
Since the original issue is only reproducible with ffmpeg 3.4.2, but not with 3.3.2 and also not with current snapshot, I will close this issue here. It seems to be an ffmpeg issue.

**Comment by 9000h** [comment]
as long as there is no known workaround ffmpeg 3.4.2 should be avoided :-(
