### ISSUE TITLE
1080p videos take 1080i settings

### ISSUE THREAD

**Issue by mighty-p** [pesintta/vdr-plugin-vaapidevice#96]
Sorry for filing so many issues at the moment. I thought it is good filing everything that I noticed. This should be the last one for the moment :)

I noticed that for DVB-T2 channels, which are sent here in 1080**p** resolution, the picture is influenced by the settings that I do for 1080**i**. I was surprised that the settings for an interlaced resolution are actually applied here for a progressive one (even if the number of lines are the same). Actually, I thought the UHD settings would apply, although 1080p is also not UHD, so this would also not be the best fit. Maybe there should be separate settings for 1080p, or alternatively the 1080i section should be renamed to "1080i/1080p".

**Comment by rofafor** [comment]
Could you check whether the linked pull requests fixes your problems? I don't have 1080p samples available, so I cannot check the current functionality of interlace detection.

**Comment by mighty-p** [comment]
Unfortunately, I am currently not at the location with my vdr with DVB-T2 reception. I probably won't be able to test this before Saturday.

**Comment by mighty-p** [comment]
Unfortunately, for me even with this change, 1080p takes the 1080i settings, not the 1080i ones.

**Comment by mighty-p** [comment]
not sure why I cannot re-open this issue.

**Comment by rofafor** [comment]
Please, provide a short video sample.

**Comment by mighty-p** [comment]
[00001.ts.gz](https://github.com/pesintta/vdr-plugin-vaapidevice/files/1820853/00001.ts.gz)

**Comment by rofafor** [comment]
This might help: https://github.com/pesintta/vdr-plugin-vaapidevice/pull/112

**Comment by mighty-p** [comment]
I confirm that this helped. Thanks a lot!
